package ua.kapitonenko.app.domain;

import ua.kapitonenko.app.config.keys.Keys;

/**
 * Enumerates all supported types of {@link Report}.
 */
public enum ReportType {
	
	/**
	 * In memory report. Does not change the state of the system.
	 */
	X_REPORT(Keys.X_REPORT),
	
	/**
	 * All the data, generated by the report, has to be stored in database.
	 */
	Z_REPORT(Keys.Z_REPORT);
	
	String label;
	
	ReportType(String label) {
		this.label = label;
	}
	
	public String getLabel() {
		return label;
	}
}
